### ISSUE TITLE
這有辦法解析嗎?

### ISSUE THREAD

**Issue by goodneo** [xyuanmu/parseiqiyi#2]
想問一下喔  愛奇藝上這種要用搜尋才能看的影片
有辦法解析嗎?
http://so.iqiyi.com/so/q_%E5%BF%85%E5%A8%B6%E5%A5%B3%E4%BA%BA?source=hot&sr=1093136565600

**Comment by xyuanmu** [comment]
搜到的如果是爱奇艺的就可以解析，其他网站的不能。
这个工具能解析的网站比较全：https://github.com/soimort/you-get

**Comment by goodneo** [comment]
有稍微看過 但不太懂該怎用  windows下能用嗎
可否教一下?

**Comment by xyuanmu** [comment]
Windows 下可以用，使用方法：
- 首先下載 [python3](https://www.python.org/downloads/release/python-351/)，最好是便攜版：**Windows x86-64 embeddable zip file**，然後解壓到一個路徑，如：C:\Python3
- 下载 you-get，解压到另一個路徑，如：C:\you-get
- 打開記事本：輸入下面的代码，保存為 youget.bat：

``` shell
@echo off

:you_get
echo.
set /p url=input url: 
echo.
"C:\Python3\python.exe" "C:\you-get\you-get" %url%
pause
call :you_get
```

以後運行 youget.bat 輸入網址就可以下載，或者在網址前加 -i 查看信息。如輸入：
`-i http://www.acfun.tv/v/ac2302711` 會提示你下載的格式和命令。
有些視頻需要合併的，需要 [ffmpeg](http://ffmpeg.zeranoe.com/builds/)，下載static版本，解壓 bin 目錄的 ffmpeg.exe 到 you-get 目錄即可。

**Comment by Vicyyw** [comment]
大神 用这种方法爱奇艺不能下载了···

**Comment by xyuanmu** [comment]
@Vicyyw 哪种方法？you-get 还是 php，刚才测试了都正常。另外说明下，爱奇艺视频地址有效时间为10分钟，you-get 不会自动解析，过期后需要重新下载，会读取已下载好的文件。

**Comment by Vicyyw** [comment]
谢谢大神，今天再试果然能成功下载爱奇艺了，用的是you-get。但是也存在了问题。

1.我用 -i+url下载爱奇艺，发现即使我是会员，也只能下载超高清（720p），无法下载1080p
EX：http://www.iqiyi.com/v_19rrl7gc34.html#vfrm=2-3-0-1
只有超高清，高清，标清，最差，木有1080p选项

2.用you-get下载搜狐和腾讯视频，会有失败代码产生
EX：腾讯
input url: -i http://v.qq.com/cover/4/4wom3bt7i62upqf.html?vid=a00192t11k6

you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

3.下载新浪，腾讯视频发现不能选择画质。EX：
腾讯
input url: -i http://v.qq.com/cover/8/8h0za1a56887tt9.html
Site:       QQ.com
Title:      贾乃亮一家回老家过年 甜馨大王来哈尔滨巡山
Type:       MPEG-4 video (video/mp4)
Size:       4.29 MiB (4494251 Bytes)

新浪
http://video.sina.com.cn/p/news/s/v/2016-02-04/114165181855.html
Site:       Sina.com
Title:      美人鱼：水下摄影的窒息之美
Type:       Flash video (video/x-flv)
Size:       21.69 MiB (22742858 Bytes)

实际下载后测试发现对应的都是高清版，腾讯的720p和新浪的原画选择不了。土豆其实也不能选择画质，但是默认的是最高的。

按照大神指点，我输入的编码是：
@echo off

:you_get
echo.
set /p url=input url: 
echo.
"E:\python3\python.exe" "E:\you-get\you-get" %url%
pause
call :you_get

python版本是3.4

后面两个其实不是大问题，主要是爱奇艺的1080p的问题。是否因为you-get下载不了1080p呢，不知道哪里出错了···

**Comment by xyuanmu** [comment]
@Vicyyw you-get 是可以下载1080P的，至于解析不出来，我也不知道原因。

```
请输入命令/地址: -i http://www.iqiyi.com/v_19rrl7gc34.html

site:                爱奇艺 (Iqiyi)
title:               《2016东方跨年》赵丽颖&张艺兴《倔强》
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        fullhd
      container:     f4v
      video-profile: 全高清
      size:          62.5 MiB (65518576 bytes)
    # download-with: you-get --format=fullhd [URL]
```

**Comment by Vicyyw** [comment]
@xyuanmu   大神，关于合并想请教
我单单把 bin 目录的 ffmpeg.exe 到 you-get 文件夹里面
发现无法合并，下载完成后就马上出现错误，不知道哪里出了问题，用you-get可以下载完成
ffmpeg的环境变量我还没设置，是否需要呢

��████████████████████┤[83/83]    3 MB/s�███████┤[83/83]    3 MB/s83/83]    3 MB
 100% (898.4/898.4MB) ├███████████████████████████████████████┤[83/83]    4 MB/s
��████████████████████┤[83/83]    4 MB/s�███████┤[83/83]    4 MB/s83/83]    4 MB
/s
**Merging video parts...
.\超级汽车LeSEE实车震撼亮相 开启生态汽车时代[00].mp4
� 开启生态汽车时代[00].mp4
时代[00].mp4
p4**
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
地址是 http://www.le.com/ptv/vplay/25173807.html?ch=le420_nryy

又用爱奇艺试了一下发现竟然可以合并。那就是自动解压，不需要设置环境变量就能用了吧
然后又去you-get那边找了下，发现也有人遇到乐视的视频不能合并的情况···
还有 看到他们的代码里面 开头是$  好奇想问一下，这是什么意思呢

**Comment by xyuanmu** [comment]
乐视经常会出现不能合并，而且视频分块也多，我一般用硕鼠下载。Linux终端命令开头就是 $，跟 Win 系统 > 一个道理。

**Comment by Vicyyw** [comment]
@xyuanmu  原来如此，懂了，关键硕鼠下不到免费1080P的哈。
